set identity_insert GNRL_FIRSTADMINDIVISION on

insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16484,'AK','Alaska',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16485,'AR','Arkansas',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16486,'AZ','Arizona',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16487,'CO','Colorado',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16488,'FL','Florida',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16489,'KS','Kansas',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16490,'MD','Maryland',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16491,'MN','Minnesota',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16492,'MO','Missouri',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16493,'MS','Mississippi',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16494,'MT','Montana',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16495,'NM','New Mexico',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16496,'NY','New York',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16497,'PA','Pennsylvania',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16498,'PR','Puerto Rico',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16499,'RI','Rhode Island',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16500,'SC','South Carolina',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16501,'TN','Tennessee',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16502,'TX','Texas',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16503,'UT','Utah',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16504,'VA','Virginia',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16505,'WV','West Virginia',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16506,'AL','Alabama',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16507,'CA','California',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16508,'CT','Connecticut',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16509,'DC','Washington, D.C.',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16510,'DE','Delaware',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16511,'GA','Georgia',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16512,'HI','Hawaii',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16513,'IA','Iowa',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16514,'ID','Idaho',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16515,'IL','Illinois',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16516,'IN','Indiana',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16517,'KY','Kentucky',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16518,'LA','Louisiana',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16519,'MA','Massachusetts',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16520,'ME','Maine',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16521,'MI','Michigan',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16522,'NC','North Carolina',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16523,'ND','North Dakota',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16524,'NE','Nebraska',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16525,'NH','New Hampshire',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16526,'NJ','New Jersey',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16527,'NV','Nevada',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16528,'OH','Ohio',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16529,'OK','Oklahoma',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16530,'OR','Oregon',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16531,'SD','South Dakota',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16532,'VT','Vermont',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16533,'WA','Washington',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16534,'WI','Wisconsin',69
insert into GNRL_FIRSTADMINDIVISION (FIRSTADMINDIVISIONID,ABBREVIATION,NAME,COUNTRYID) select 16535,'WY','Wyoming',69

set identity_insert GNRL_FIRSTADMINDIVISION off