/*-- BEGIN Address Type --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 101,'User Type'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 101001,'','Home','Home Address',1,1,101
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 101002,'','Work','Work Address',2,1,101
/*-- END Address Type --*/