/*-- BEGIN User Type --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 112,'ContactRegard'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 112001,'','Order Modification','Order Modification',1,1,112
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 112002,'','Add New School User','Add New School User',2,1,112
/*-- END User Type --*/