/*-- BEGIN Password Format Type --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 103,'Password Format Type'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 103001,'','Plain','Plain Text',1,1,103
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 103002,'','Md5','Md5',2,1,103
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 103003,'','Sha1','Sha1',2,1,103
/*-- END Password Format Type --*/