/*-- BEGIN Meal Type --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 110,'Meal Type'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 110001,'','Breakfast','Breakfast',1,1,110
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 110002,'','Snack','Snack',2,1,110
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 110003,'','Lunch','Lunch',3,1,110
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 110004,'','SackLunch','Sack Lunch',4,1,110
/*-- END Meal Type --*/