/*-- BEGIN Algorithm Type --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 104,'Measurement Type'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 104001,'','None','None',1,1,104
/*-- END Algorithm Type --*/