/*-- BEGIN User Type --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 111,'User Type'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 111001,'','Company','Company Users',1,1,111
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 111002,'','Client','School Users',2,1,111
/*-- END User Type --*/