/*-- BEGIN Record Status --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 102,'Record Status'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 102001,'','Active','active record',1,1,102
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 102002,'','InActive','inactive record',2,1,102
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 102003,'','Deleted','deleted record',3,1,102
/*-- BEGIN Record Status --*/