/*-- BEGIN Algorithm Type --*/
insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 105,'Algorithm Type'
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 105001,'','None','None',1,1,105
/*-- END Algorithm Type --*/