/*-- BEGIN Food Type --*/

insert into GNRL_LOOKUPGROUP (LOOKUPGROUPID,NAME) select 106,'Food Type'

insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 106001,'','Milk','Milk',1,1,106
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 106002,'','Fruit','Fruit',2,1,106
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 106003,'','Grain','Grain',3,1,106
insert into GNRL_LOOKUPITEM (LOOKUPITEMID,FIELDVALUE,FIELDTEXT,DESCRIPTION,ITEMORDER,ISACTIVE,LOOKUPGROUPID) select 106004,'','Meat Alternative','Meat Alternative',4,1,106

/*-- END Food Type --*/